services:
  app:
    build: 
      context: .
      args:
        NAME: World
    platform: linux/arm64
    ports:
      - "8000:80"

x-topo:
  name: "Topo Welcome"
  description: |
    A Hello World web app to test Topo setup

  features: []

  args:
    NAME:
      description: The person to greet
      required: true
      example: "World"
